- name: Mount squashfs image from root partition
  become: true
  mount:
    name: "{{ vyos_read_root }}"
    src: "{{ vyos_write_root }}/boot/{{ vyos_version }}/{{ vyos_version }}.squashfs"
    fstype: squashfs
    opts: loop,ro
    state: mounted

- name: create work dir for overlayfs
  ansible.builtin.file:
    path: "{{ vyos_write_root_workdir }}"
    state: directory

- name: Set up union overlayfs for post installation tasks
  become: true
  mount:
    name: "{{ vyos_install_root }}"
    src: overlay
    fstype: overlay
    opts: "lowerdir=noatime,{{ vyos_read_root }},upperdir={{ vyos_write_root }}/boot/{{ vyos_version }}/rw,workdir={{ vyos_write_root_workdir }}"
    state: mounted

